version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - playground_devops
    environment:
      REDIS_PASSWORD: password
    volumes:
      - redis_data:/bitnami/redis/data
    restart: unless-stopped

networks:
  playground_devops:
    driver: bridge

volumes:
  redis_data:

