version: "3.9"

services:
  container:
    image: alpine:3
    container_name: resource-limit
    command:
      - "sleep 20"
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 64M
        limits:
          cpus: "0.2"
          memory: 128M
