apiVersion: v1
kind: ConfigMap
metadata:
  name: playground-config
  labels:
    app.kubernetes.io/name: playground
data:
  some-script.sh: |-
    #!/bin/sh
    export MESSAGE="Hello World!"
    printenv
    sleep 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app.kubernetes.io/name: playground
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: playground
    spec:
      containers:
        - name: playground-container
          image: alpine:3
          command:
            - "/bin/sh"
          args:
            - "/bin/some-script.sh"
          volumeMounts:
            - name: playground-volume
              mountPath: /bin/some-script.sh
              subPathExpr: some-script.sh
              readOnly: true
      volumes:
        - name: playground-volume
          configMap:
            name: playground-config
            defaultMode: 0700
