---
- name: Debug box installation
  hosts: 127.0.0.1
  become: true

  tasks:
    - name: Get list of files on root path
      shell: ls -l
      register: files_found

    - name: Print list of files on root path
      debug:
        var: files_found
