Vagrant.configure("2") do |config|
   config.vm.box = "com.example/packer-ansible-vagrant"
   config.vm.network "private_network", ip: "192.168.56.200"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus = 2
   end
 end
