apiVersion: v1
kind: PersistentVolume
metadata:
  name: playground-pv
spec:
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: 1Gi
  hostPath:
    path: "/playground"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playground-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
  volumeName: playground-pv
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app.kubernetes.io/name: playground
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: playground
    spec:
      containers:
      - name: playground-container
        image: alpine:3
        volumeMounts:
          - name: playground-volume
            mountPath: /mnt
      volumes:
        - name: playground-volume
          persistentVolumeClaim:
              claimName: playground-pvc
